export const projects = [
  {
    title: "AI Software Stack",
    company: "CORSAIR",
    period: "07/2025 - Present",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Developed a web-based app installer with real-time SignalR updates and deep integration to a C# backend. Delivered fast and user-friendly enterprise deployments.",
    responsibilities: [
      "Developed and maintained AngularJS components, directives, and services to implement key features of the resource management system.",
      "Built reusable shared modules to standardize interfaces and streamline data handling across the frontend.",
      "Implemented two-way data binding and dynamic form handling for managing employee and project data.",
      "Created interactive charts and dashboards to visualize resource allocation, cost, and time tracking.",
      "Collaborated closely with backend developers and UI/UX designers to improve usability and maintain consistency.",
    ],
    technologies: ["React.js", "SignalR", "Bootstrap (C#)"],
    images: [
      "/images/projects/warp/1.png",
      "/images/projects/warp/2.png",
      "/images/projects/warp/3.png",
    ],
  },
  {
    title: "Magicblocks AI Chatbot",
    company: "MagicBlocks, Inc.",
    period: "03/2024 - 06/2025",
    type: "Full time",
    position: "Full Stack Developer",
    description:
      "Engineered an embeddable AI chatbot platform with strong authentication, multi-channel agent support, and performance optimization using Cloudflare and Vercel.",
    responsibilities: [
      "Built shared modular packages including database schema and reusable interface components to support scalable development.",
      "Implemented and improved UI/UX for interactive bot widgets.",
      "Developed responsive interfaces optimized for desktop, tablet, and mobile.",
      "Set up and integrated multi-channel communication for the AI Agent including Twilio and Instagram.",
      "Optimized backend performance using Cloudflare caching and efficient API request handling, improving data delivery speed.",
      "Acted as a key problem solver, diagnosing complex technical issues across both frontend and backend layers.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Oauth2",
      "AWS",
      "Vercel",
      "MySQL",
      "MongoDB",
      "Cloudflare",
    ],
    images: [
      "/images/projects/magicblocks/1.png",
      "/images/projects/magicblocks/2.png",
      "/images/projects/magicblocks/3.png",
    ],
  },
  {
    title: "Tinda Job",
    company: "AZUBI IN GERMANY",
    period: "12/2024 - 04/2025",
    type: "Contract",
    position: "Mobile Developer - Project Manager",
    description:
      "Led development and project management for a mobile app connecting companies and job seekers, using Agile methodology and React Native.",
    responsibilities: [
      "Worked directly with client stakeholders and led project planning using Agile.",
      "Designed UI/UX system and component structure for a scalable mobile app experience.",
      "Set up core development workflows including GitHub, Jira, and Confluence.",
      "Built the initial React Native (Expo) codebase and prepared CI-friendly app structure.",
      "Developed and integrated frontend features in collaboration with the backend team.",
      "Provided technical leadership and requirement clarification to team members.",
    ],
    technologies: [
      "React Native (Expo)",
      "Node.js",
      "MongoDB",
      "Docker",
      "Cloudflare R2",
      "Twilio",
    ],
    images: [
      "/images/projects/tinda/1.png",
      "/images/projects/tinda/2.png",
      "/images/projects/tinda/3.png",
    ],
  },
  {
    title: "HYP 3",
    company: "DTC Labs",
    period: "04/2024 - 07/2024",
    type: "Contract",
    position: "Frontend Developer",
    description:
      "Developed a scalable crypto trading and news platform with Next.js, integrating Web3 wallet support and focusing on speed, SEO, and UI/UX improvements.",
    responsibilities: [
      "Lead the frontend development of a crypto trading and news platform",
      "Integrate Privy wallet for Web3 authentication",
      "Build UI and integrate features with Backend team",
      "Optimize performance in Frontend side",
      "Support team members about technical and requirements",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Golang",
      "PostgreSQL",
      "Docker",
      "Privy Wallet",
      "Web3",
    ],
    images: [
      "/images/projects/hyp3/1.png",
      "/images/projects/hyp3/2.png",
      "/images/projects/hyp3/3.png",
    ],
  },
  {
    title: "Block24",
    company: "TradecoinVN",
    period: "09/2023 - 03/2024",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Developed a scalable crypto trading and news platform with Next.js, integrating Web3 wallet support and focusing on speed, SEO, and UI/UX improvements.",
    responsibilities: [
      "Optimized frontend performance to ensure faster load times and smoother user interactions across devices.",
      "Enhanced UI/UX design to improve engagement and accessibility for a global user base.",
      "Collaborated with cross-functional teams to design intuitive user flows that attract and retain users.",
      "Resolved complex frontend issues, ensuring stability and scalability in production environments.",
      "Refactored and modularized existing code to improve maintainability and long-term scalability.",
      "Implemented a Redux-based state management system for consistent data handling across components.",
      "Supported teammates through code reviews, documentation, and technical guidance.",
    ],
    technologies: [
      "Next.js",
      "Oauth2",
      "Node.js",
      "MySQL",
      "Docker",
      "Cloudflare",
    ],
    images: [
      "/images/projects/block24/1.png",
      "/images/projects/block24/2.png",
      "/images/projects/block24/3.png",
    ],
  },
  // {
  //   title: "Game Application",
  //   company: "Freelance",
  //   period: "12/2022 - 07/2023",
  //   type: "Contract",
  //   position: "Full Stack Developer",
  //   description:
  //     "Built a multiplayer gaming platform with real-time play, secure cash transactions, low-latency Socket.io, and seamless integration with external services.",
  //   responsibilities: [
  //     "Build and optimize the complex UI components using Next.js, NextAuth.js, and Tailwind CSS, enhancing performance and maintainability",
  //     "Design database flow with MySQL and MongoDB",
  //     "Build RESTful APIs with Node.js and Socket.io, reducing real-time latency by 150ms, leading to smoother and faster interactions",
  //     "Config Firebase to store files",
  //     "Setup Seamless APIs for integrating to another platform",
  //     "Setup and manage project deployments by using aaPanel, ensuring reliable server management and maintenance",
  //   ],
  //   technologies: [
  //     "Next.js",
  //     "NextAuth.js",
  //     "Socket.io",
  //     "Node.js",
  //     "MySQL",
  //     "MongoDB",
  //     "Firebase",
  //   ],
  //   images: [
  //     "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop",
  //     "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&h=600&fit=crop",
  //     "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop",
  //   ],
  // },
  {
    title: "Order Food",
    company: "Cardwatch POS",
    period: "01/2022 - 11/2022",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Created a modular food ordering and POS app, published a reusable UI library, and enabled seamless printing and offline PWA support.",
    responsibilities: [
      "Built and optimized complex UI components using Next.js and Tailwind CSS, improving performance and maintainability.",
      "Designed and structured scalable database flows with MySQL and MongoDB.",
      "Developed RESTful APIs with Node.js and real-time services using Socket.io, reducing latency by 150ms for smoother gameplay.",
      "Configured Firebase for secure file and asset storage.",
      "Implemented integration APIs for external platform connectivity.",
      "Managed deployment and server administration using aaPanel, ensuring reliable performance and system uptime.",
    ],
    technologies: ["Next.js", "PWA", "Java", "PostgreSQL", "Docker", "Nginx"],
    images: [
      "/images/projects/cardwatch/1.png",
      "/images/projects/cardwatch/2.png",
      "/images/projects/cardwatch/3.png",
    ],
  },
];
