export const projects = [
  {
    title: "Warp AI",
    company: "Hiptech Solution",
    period: "07/2025 - Present",
    type: "Full time",
    position: "Frontend Developer",
    description: "Build system for allow install application from website.",
    responsibilities: [
      "Build UI and setup source",
      "Handle realtime connection by SignalR",
      "Integration with Bootstrap to send and retrieve installation events",
      "Config package file for some applications by Power Shell",
    ],
    technologies: ["React.js", "SignalR", "Bootstrap (C#)"],
  },
  {
    title: "Magicblocks AI",
    company: "Hiptech Solution",
    period: "03/2024 - 06/2025",
    type: "Full time",
    position: "Full Stack Developer",
    description:
      "Build and provide AI bot services for websites in embedded form",
    responsibilities: [
      "Build local shared packages like database and interfaces",
      "Implement and improve UI/UX",
      "Develop friendly interfaces that adapt to multiple devices like desktop, tablet and mobile",
      "Setup and integrate channels for Agent like Twilio and Instagram",
      "Optimize data processing by caching in Cloudflare and API request",
      "Problem solver",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Oauth2",
      "AWS",
      "Vercel",
      "MySQL",
      "MongoDB",
      "Cloudflare",
    ],
  },
  {
    title: "Tinda",
    company: "Azubi",
    period: "12/2024 - 04/2025",
    type: "Contract",
    position: "Frontend Developer - Project Manager",
    description:
      "Build mobile application for a center that connects between companies and job seekers.",
    responsibilities: [
      "Work directly with client and make a full plain with Agile",
      "Design system for application",
      "Setup working source like Github, Jira and Confluence",
      "Setup source code for React Native app",
      "Build UI and integrate features with Backend team",
      "Support team members about technical and requirements",
    ],
    technologies: [
      "React Native (Expo)",
      "Node.js",
      "MongoDB",
      "Docker",
      "Cloudflare R2",
      "Twilio",
    ],
  },
  {
    title: "Block24",
    company: "TradecoinVN",
    period: "09/2023 - 03/2024",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Website that connects to a huge of users and traders. It gives a lot of knowledege and experience in trading",
    responsibilities: [
      "Optimize performance in Frontend side",
      "Improve UI and UX",
      "Collaborate with team members to define and improve flows to attract users",
      "Resolve high and complex issues",
      "Connect Web3 wallet",
      "Clean and refactor the source for scalability",
      "Support team members",
    ],
    technologies: [
      "Next.js",
      "Oauth2",
      "Node.js",
      "MySQL",
      "Docker",
      "Cloudflare",
    ],
  },
  {
    title: "Game Application",
    company: "Freelance",
    period: "12/2022 - 07/2023",
    type: "Contract",
    position: "Full Stack Developer",
    description:
      "Application that supports multiple players, realtime and seamless cash. It allows to integrate to another website game platform",
    responsibilities: [
      "Build and optimize the complex UI components using Next.js, NextAuth.js, and Tailwind CSS, enhancing performance and maintainability",
      "Design database flow with MySQL and MongoDB",
      "Build RESTful APIs with Node.js and Socket.io, reducing real-time latency by 150ms, leading to smoother and faster interactions",
      "Config Firebase to store files",
      "Setup Seamless APIs for integrating to another platform",
      "Setup and manage project deployments by using aaPanel, ensuring reliable server management and maintenance",
    ],
    technologies: [
      "Next.js",
      "NextAuth.js",
      "Socket.io",
      "Node.js",
      "MySQL",
      "MongoDB",
      "Firebase",
    ],
  },
  {
    title: "Order Food - Cardwatch POS",
    company: "Cardwatch",
    period: "01/2022 - 11/2022",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Ordering food application that supports for members in the specific community",
    responsibilities: [
      "Build codebase, code review, problem solver",
      "Lead the frontend development of a POS system used by a Canadian agency, streamlining customer management and order processing",
      "Build a reusable UI component library (published), reducing development time for new features by 50%",
      "Research and integrate CPOS printer support, allowing seamless transaction printing directly from the platform",
    ],
    technologies: ["Next.js", "PWA", "Java", "PostgreSQL", "Docker", "Nginx"],
  },
];
