export const projects = [
  {
    title: "Warp AI",
    company: "Hiptech Solution",
    period: "07/2025 - Present",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Developed a web-based app installer with real-time SignalR updates and deep integration to a C# backend. Delivered fast and user-friendly enterprise deployments.",
    responsibilities: [
      "Build UI and setup source",
      "Handle realtime connection by SignalR",
      "Integration with Bootstrap to send and retrieve installation events",
      "Config package file for some applications by Power Shell",
    ],
    technologies: ["React.js", "SignalR", "Bootstrap (C#)"],
    images: [
      "/images/projects/warp/1.png",
      "/images/projects/warp/2.png",
      "/images/projects/warp/3.png",
    ],
  },
  {
    title: "Magicblocks AI Chatbot",
    company: "MagicBlocks, Inc.",
    period: "03/2024 - 06/2025",
    type: "Full time",
    position: "Full Stack Developer",
    description:
      "Engineered an embeddable AI chatbot platform with strong authentication, multi-channel agent support, and performance optimization using Cloudflare and Vercel.",
    responsibilities: [
      "Build local shared packages like database and interfaces",
      "Implement and improve UI/UX",
      "Develop friendly interfaces that adapt to multiple devices like desktop, tablet and mobile",
      "Setup and integrate channels for Agent like Twilio and Instagram",
      "Optimize data processing by caching in Cloudflare and API request",
      "Problem solver",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Oauth2",
      "AWS",
      "Vercel",
      "MySQL",
      "MongoDB",
      "Cloudflare",
    ],
    images: [
      "/images/projects/magicblocks/1.png",
      "/images/projects/magicblocks/2.png",
      "/images/projects/magicblocks/3.png",
    ],
  },
  {
    title: "Tinda Job",
    company: "AZUBI IN GERMANY",
    period: "12/2024 - 04/2025",
    type: "Contract",
    position: "Mobile Developer - Project Manager",
    description:
      "Led development and project management for a mobile app connecting companies and job seekers, using Agile methodology and React Native.",
    responsibilities: [
      "Work directly with client and make a full plain with Agile",
      "Design system for application",
      "Setup working source like Github, Jira and Confluence",
      "Setup source code for React Native app",
      "Build UI and integrate features with Backend team",
      "Support team members about technical and requirements",
    ],
    technologies: [
      "React Native (Expo)",
      "Node.js",
      "MongoDB",
      "Docker",
      "Cloudflare R2",
      "Twilio",
    ],
    images: [
      "/images/projects/tinda/1.png",
      "/images/projects/tinda/2.png",
      "/images/projects/tinda/3.png",
    ],
  },
  {
    title: "Block24",
    company: "TradecoinVN",
    period: "09/2023 - 03/2024",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Developed a scalable crypto trading and news platform with Next.js, integrating Web3 wallet support and focusing on speed, SEO, and UI/UX improvements.",
    responsibilities: [
      "Optimize performance in Frontend side",
      "Improve UI and UX",
      "Collaborate with team members to define and improve flows to attract users",
      "Resolve high and complex issues",
      "Connect Web3 wallet",
      "Clean and refactor the source for scalability",
      "Support team members",
    ],
    technologies: [
      "Next.js",
      "Oauth2",
      "Node.js",
      "MySQL",
      "Docker",
      "Cloudflare",
    ],
    images: [
      "/images/projects/block24/1.png",
      "/images/projects/block24/2.png",
      "/images/projects/block24/3.png",
    ],
  },
  // {
  //   title: "Game Application",
  //   company: "Freelance",
  //   period: "12/2022 - 07/2023",
  //   type: "Contract",
  //   position: "Full Stack Developer",
  //   description:
  //     "Built a multiplayer gaming platform with real-time play, secure cash transactions, low-latency Socket.io, and seamless integration with external services.",
  //   responsibilities: [
  //     "Build and optimize the complex UI components using Next.js, NextAuth.js, and Tailwind CSS, enhancing performance and maintainability",
  //     "Design database flow with MySQL and MongoDB",
  //     "Build RESTful APIs with Node.js and Socket.io, reducing real-time latency by 150ms, leading to smoother and faster interactions",
  //     "Config Firebase to store files",
  //     "Setup Seamless APIs for integrating to another platform",
  //     "Setup and manage project deployments by using aaPanel, ensuring reliable server management and maintenance",
  //   ],
  //   technologies: [
  //     "Next.js",
  //     "NextAuth.js",
  //     "Socket.io",
  //     "Node.js",
  //     "MySQL",
  //     "MongoDB",
  //     "Firebase",
  //   ],
  //   images: [
  //     "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop",
  //     "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&h=600&fit=crop",
  //     "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop",
  //   ],
  // },
  {
    title: "Order Food - Cardwatch POS",
    company: "Cardwatch",
    period: "01/2022 - 11/2022",
    type: "Full time",
    position: "Frontend Developer",
    description:
      "Created a modular food ordering and POS app, published a reusable UI library, and enabled seamless printing and offline PWA support.",
    responsibilities: [
      "Build codebase, code review, problem solver",
      "Lead the frontend development of a POS system used by a Canadian agency, streamlining customer management and order processing",
      "Build a reusable UI component library (published), reducing development time for new features by 50%",
      "Research and integrate CPOS printer support, allowing seamless transaction printing directly from the platform",
    ],
    technologies: ["Next.js", "PWA", "Java", "PostgreSQL", "Docker", "Nginx"],
    images: [
      "/images/projects/cardwatch/1.png",
      "/images/projects/cardwatch/2.png",
      "/images/projects/cardwatch/3.png",
    ],
  },
];
